import * as Rules from '../core/rules.js';
import {enemies} from '../core/content.js';
import {normalizeResolution,resolveRenderResolution} from './display-settings.js';
import {ENTITY_ART} from './entity-art.js';
import {EntityMotion} from './entity-motion.js';

const TAU=Math.PI*2, TILT=55*Math.PI/180, S=Math.sin(TILT), C=Math.cos(TILT), HEIGHT=.95;
const COLORS={mint:'#79dfc1',coral:'#f18478',gold:'#ead28c',ink:'#10292c',ivory:'#eee7d4'};
const TOWERS=['anchor_bulwark','phase_blade','boundary_riveter','resonance_guard','pulse_array','focus_rail','arc_mortar','drone_loom','bandwidth_relay','memory_mechanic','frequency_choir','resistance_beacon'];
const ENEMIES=['static_drifter','spike_runner','shield_echo','tempo_amplifier','fracture_seed','floating_noise','remote_hunter','siege_ram','memory_medic','bandwidth_jammer','phase_teleporter','replication_node','pressure_cantor','armored_worm','shield_conductor','signal_summoner','resistance_corruptor','detonation_shell','frequency_hunter','terrain_dismantler','proliferation_protocol','spirit_taxer','noise_hive','mirror_censor','memory_reforger','bandwidth_requisitioner','chorus_overseer','zero_frequency_mind'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function wrapAngle(a){return (a%TAU+TAU)%TAU;}
// Geometry and input use CSS pixels. Only the backing store uses device pixels;
// the cap keeps large/high-DPI displays from multiplying terrain fill work.
export function renderResolution(width,height,dpr=1){const {resolution,...size}=resolveRenderResolution({cssWidth:width,cssHeight:height,windowWidth:width,windowHeight:height,dpr,resolution:'auto'});return size;}
export function rangeBoundary(cells){const occupied=new Set(cells.map(c=>`${c.x},${c.z}`)),edges=[];for(const c of cells)for(const [dx,dz,a,b]of [[0,-1,[0,0],[1,0]],[1,0,[1,0],[1,1]],[0,1,[1,1],[0,1]],[-1,0,[0,1],[0,0]]])if(!occupied.has(`${c.x+dx},${c.z+dz}`))edges.push({x:c.x,z:c.z,a,b});return edges;}
export function worldToScreen(x,z,h,camera){const dx=x-camera.x,dz=z-camera.z,c=Math.cos(camera.yaw),s=Math.sin(camera.yaw);return {x:camera.width/2+(dx*c-dz*s)*camera.scale,y:camera.height/2+((dx*s+dz*c)*S-h*HEIGHT*C)*camera.scale};}
export function screenToGround(x,y,h,camera){const u=(x-camera.width/2)/camera.scale,v=((y-camera.height/2)/camera.scale+h*HEIGHT*C)/S,c=Math.cos(camera.yaw),s=Math.sin(camera.yaw);return {x:camera.x+u*c+v*s,z:camera.z-u*s+v*c};}
export function panScreen(camera,dx,dy){const c=Math.cos(camera.yaw),s=Math.sin(camera.yaw),u=dx/camera.scale,v=dy/(camera.scale*S);camera.x+=u*c+v*s;camera.z+=-u*s+v*c;return camera;}
// The authored front faces world +Z. The atlas and world use the same 55° view.
export function directionFrame(dx,dz,yaw,bearing=0){return Math.round(wrapAngle(Math.atan2(dx,dz)-yaw+bearing)/TAU*8)%8;}
export function cameraStep(camera,keys,dt){const delta=clamp(dt,0,.05),dx=(keys.has('d')?1:0)-(keys.has('a')?1:0),dy=(keys.has('s')?1:0)-(keys.has('w')?1:0),turn=(keys.has('e')?1:0)-(keys.has('q')?1:0);camera.yaw=wrapAngle(camera.yaw+turn*Math.PI/2*delta);if(dx||dy)panScreen(camera,dx*150*delta,dy*150*delta);return !!(dx||dy||turn);}
function polygon(ctx,points,fill,stroke,width=1){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.lineWidth=width;ctx.strokeStyle=stroke;ctx.stroke();}}
function line(ctx,points,color,width=1){if(!points.length)return;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function hash(x,z){let v=Math.imul(x+319,374761393)^Math.imul(z+711,668265263);v=(v^(v>>>13))*1274126177;return ((v^(v>>>16))>>>0)/4294967296;}
function makeCanvas(){return document.createElement('canvas');}

/** A presentation-only orthographic battlefield. All game verdicts come from Rules. */
export class Battlefield{
  constructor(canvas,{onCell=()=>{},onHover=()=>{},onCancel=()=>{},onError=()=>{}}={}){
    this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.callbacks={onCell,onHover,onCancel,onError};
    this.camera={x:20,z:21,yaw:Math.PI/4,scale:8,width:640,height:400};this.zoomLevel=1;this.state=null;this.selection={};this.pointer=null;this.hover=null;this.keys=new Set();this.effects=[];this.images=new Map();this.errors=[];this.lastTime=0;this.dirty=true;this.cache=makeCanvas();this.tiles=[];this.tileBuckets=new Map();this.paths=[];this.range=[];this.rangeKey='';this.listeners=[];this.isDragging=false;this.interactive=false;this.encounter=null;this.pathTerrain=null;this.pathRevision=-1;this.facings=new Map();this.positions=new Map();
    this.worldLabels=[];this.entityBoxes=[];this.rangeBlocked=[];this.rangeEdges=[];this.rangeBlockedEdges=[];this.resolution='auto';this.pointerClient=null;this.entityMotion=new EntityMotion();this.entityFrames=[];
    canvas.tabIndex=0;canvas.setAttribute('aria-label','战场。WASD平移，Q/E旋转，滚轮缩放，F回到火种，右键取消。');canvas.style.touchAction='none';canvas.style.imageRendering='auto';
    for(const id of [...TOWERS,...ENEMIES]){const art=ENTITY_ART[id],img=new Image();img.onload=()=>{if(img.naturalWidth!==art.cell*art.directions||img.naturalHeight!==art.cell*art.rows)this.reportError(`动作图集尺寸错误：${id}`);};img.onerror=()=>this.reportError(`动作素材加载失败：${id}`);img.src=art.animationPath;this.images.set(id,img);}
    const bind=(target,type,fn,options)=>{target.addEventListener(type,fn,options);this.listeners.push(()=>target.removeEventListener(type,fn,options));};
    bind(canvas,'pointermove',e=>{if(!this.interactive)return;const p=this.pointerPosition(e);if(this.drag){if(this.isDragging||Math.hypot(p.x-this.drag.x,p.y-this.drag.y)>5){panScreen(this.camera,this.drag.x-p.x,this.drag.y-p.y);this.drag=p;this.dirty=true;this.isDragging=true;canvas.style.cursor='grabbing';}}this.pointer=p;this.updateHover();});
    bind(canvas,'pointerdown',e=>{if(!this.interactive||![0,1].includes(e.button))return;canvas.focus({preventScroll:true});const p=this.pointerPosition(e);e.preventDefault();this.drag=p;this.dragPointer=e.pointerId;this.isDragging=false;this.pointer=p;this.updateHover();canvas.setPointerCapture(e.pointerId);});
    bind(canvas,'pointerup',e=>{if(!this.drag||e.pointerId!==this.dragPointer)return;const click=e.button===0&&!this.isDragging;this.drag=null;this.isDragging=false;canvas.style.cursor='';if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);this.pointer=this.pointerPosition(e);this.updateHover();if(click&&this.hover)this.callbacks.onCell({...this.hover});});
    bind(canvas,'pointercancel',()=>{this.drag=null;this.isDragging=false;canvas.style.cursor='';});
    bind(canvas,'pointerleave',()=>{if(!this.drag){this.pointer=null;this.hover=null;this.callbacks.onHover(null);}});
    bind(canvas,'contextmenu',e=>{if(!this.interactive)return;e.preventDefault();this.callbacks.onCancel();});
    bind(canvas,'wheel',e=>{if(!this.interactive)return;e.preventDefault();this.changeZoom(Math.exp(-e.deltaY*.0012),this.pointerPosition(e));},{passive:false});
    bind(window,'keydown',e=>{if(!this.interactive||e.ctrlKey||e.altKey||e.metaKey||['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName)||e.target?.isContentEditable)return;if(!this.canvas.isConnected||this.canvas.clientWidth===0)return;const key=e.key.toLowerCase();if(['w','a','s','d','q','e'].includes(key)){this.keys.add(key);e.preventDefault();}if(key==='f'){this.focus();e.preventDefault();}});
    bind(window,'keyup',e=>this.keys.delete(e.key.toLowerCase()));bind(window,'blur',()=>{this.keys.clear();this.drag=null;this.isDragging=false;canvas.style.cursor='';});
    this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);this.resize();
  }
  reportError(message){this.errors.push(message);this.callbacks.onError(message);}
  pointerPosition(e){const r=this.canvas.getBoundingClientRect();this.pointerClient={x:e.clientX,y:e.clientY};return {x:(e.clientX-r.left)*this.camera.width/r.width,y:(e.clientY-r.top)*this.camera.height/r.height};}
  setResolution(preset){this.resolution=normalizeResolution(preset);return this.resize();}
  resize({force=false}={}){const r=this.canvas.getBoundingClientRect();if(r.width<1||r.height<1)return false;const resolution=resolveRenderResolution({cssWidth:r.width,cssHeight:r.height,windowWidth:window.innerWidth||r.width,windowHeight:window.innerHeight||r.height,dpr:window.devicePixelRatio||1,resolution:this.resolution}),geometryChanged=this.camera.width!==resolution.width||this.camera.height!==resolution.height,bufferChanged=this.canvas.width!==resolution.pixelWidth||this.canvas.height!==resolution.pixelHeight||this.cache.width!==resolution.pixelWidth||this.cache.height!==resolution.pixelHeight;this.pixelRatio=resolution.ratio;
    // Assigning either canvas dimension clears its pixels and context, even when
    // the value is unchanged. UI refreshes must leave the current frame intact.
    if(!geometryChanged&&!bufferChanged&&!force)return false;
    if(this.canvas.width!==resolution.pixelWidth)this.canvas.width=resolution.pixelWidth;if(this.canvas.height!==resolution.pixelHeight)this.canvas.height=resolution.pixelHeight;if(this.cache.width!==resolution.pixelWidth)this.cache.width=resolution.pixelWidth;if(this.cache.height!==resolution.pixelHeight)this.cache.height=resolution.pixelHeight;
    this.camera.width=resolution.width;this.camera.height=resolution.height;this.ctx.setTransform(this.canvas.width/this.camera.width,0,0,this.canvas.height/this.camera.height,0,0);this.ctx.imageSmoothingEnabled=false;this.updateScale();this.dirty=true;
    if(geometryChanged&&this.pointerClient){const point={x:(this.pointerClient.x-r.left)*this.camera.width/r.width,y:(this.pointerClient.y-r.top)*this.camera.height/r.height};if(this.pointer)this.pointer=point;if(this.drag)this.drag={...point};}this.updateHover();return true;}
  updateScale(){const n=this.state?.terrain?.size||41;this.camera.scale=Math.min(this.camera.width/(n*1.52),this.camera.height/(n*1.3))*this.zoomLevel;}
  setState(state){const changed=this.state!==state;this.state=state;this.dirty=true;this.rangeKey='';if(changed){this.effects=[];this.facings.clear();this.positions.clear();this.encounter=null;this.entityMotion.reset();this.entityFrames=[];}this.updateScale();if(!state)this.paths=[];}
  setEncounter(encounter){this.encounter=encounter||null;}
  setInteractive(value){this.interactive=!!value;if(!this.interactive){this.keys.clear();this.drag=null;this.isDragging=false;this.pointer=null;const hadHover=this.hover;this.hover=null;this.rangeKey='';if(this.dragPointer!=null&&this.canvas.hasPointerCapture(this.dragPointer))this.canvas.releasePointerCapture(this.dragPointer);this.dragPointer=null;if(hadHover)this.callbacks.onHover(null);}this.canvas.tabIndex=this.interactive?0:-1;}
  setSelection(selection={}){if(this.selection.terrainTool!==selection.terrainTool)this.dirty=true;this.selection=selection;this.rangeKey='';this.updateHover();}
  rotate(delta){if(!Number.isFinite(delta))return;this.camera.yaw=wrapAngle(this.camera.yaw+delta);this.dirty=true;this.updateHover();}
  changeZoom(factor,point={x:this.camera.width/2,y:this.camera.height/2}){if(!Number.isFinite(factor)||factor<=0)return;const before=screenToGround(point.x,point.y,0,this.camera);this.zoomLevel=clamp(this.zoomLevel*factor,.62,3.3);this.updateScale();const after=screenToGround(point.x,point.y,0,this.camera);this.camera.x+=before.x-after.x;this.camera.z+=before.z-after.z;this.dirty=true;this.updateHover();}
  zoom(direction){this.changeZoom(direction==='in'?1.2:direction==='out'?1/1.2:1);}
  focus(){const core=this.state?Rules.coreOf(this.state):null;this.camera.x=(core?.x??20)+.5;this.camera.z=(core?.z??24)+.5;this.zoomLevel=1.1;this.updateScale();this.dirty=true;this.updateHover();}
  project(x,z,h=0){const p=worldToScreen(x,z,h,this.camera),r=this.canvas.getBoundingClientRect();return {x:p.x*r.width/this.camera.width,y:p.y*r.height/this.camera.height};}
  p(x,z,h=0){const camera=this.camera;if(this.projectionYaw!==camera.yaw){this.projectionYaw=camera.yaw;this.projectionCos=Math.cos(camera.yaw);this.projectionSin=Math.sin(camera.yaw);}const dx=x-camera.x,dz=z-camera.z,c=this.projectionCos,s=this.projectionSin;return {x:camera.width/2+(dx*c-dz*s)*camera.scale,y:camera.height/2+((dx*s+dz*c)*S-h*HEIGHT*C)*camera.scale};}
  heightAt(x,z){return this.state?Rules.cellAt(this.state,x,z)?.h||0:0;}
  updateHover(){if(!this.pointer||!this.state)return;const t=this.state.terrain;let best=null,bestDepth=-Infinity;for(let h=4;h>=0;h--){const p=screenToGround(this.pointer.x,this.pointer.y,h,this.camera),x=Math.floor(p.x),z=Math.floor(p.z);if(x<0||z<0||x>=t.size||z>=t.size||this.heightAt(x,z)!==h)continue;const depth=this.depth(x+.5,z+.5);if(depth>bestDepth){best={x,z};bestDepth=depth;}}if(best?.x!==this.hover?.x||best?.z!==this.hover?.z){this.hover=best;this.rangeKey='';this.callbacks.onHover(best?{...best}:null);}}
  depth(x,z){return x*Math.sin(this.camera.yaw)+z*Math.cos(this.camera.yaw);}
  quad(x,z,w,d,h){return [this.p(x,z,h),this.p(x+w,z,h),this.p(x+w,z+d,h),this.p(x,z+d,h)];}
  buildTerrain(){const state=this.state;if(!state)return;const {size,cells}=state.terrain,ctx=this.cache.getContext('2d');ctx.setTransform(this.cache.width/this.camera.width,0,0,this.cache.height/this.camera.height,0,0);ctx.clearRect(0,0,this.camera.width,this.camera.height);ctx.imageSmoothingEnabled=false;this.tiles=[];this.tileBuckets.clear();const c=Math.cos(this.camera.yaw),s=Math.sin(this.camera.yaw);
    for(let z=0;z<size;z++)for(let x=0;x<size;x++){const cell=cells[z*size+x],h=cell.h,q=this.quad(x,z,1,1,h),noise=hash(x,z),top=h===0?(noise>.83?'#284546':noise>.42?'#244143':'#203e40'):[null,'#426b65','#58837a','#74968a','#97ae98'][h];const sides=[];
      for(const [dx,dz,a,b] of [[0,1,3,2],[1,0,2,1],[0,-1,1,0],[-1,0,0,3]]){if(dx*s+dz*c<=.001)continue;const nx=x+dx,nz=z+dz,nh=(nx<0||nz<0||nx>=size||nz>=size)?-1.5:cells[nz*size+nx].h;if(nh>=h)continue;const corners=[[x,z],[x+1,z],[x+1,z+1],[x,z+1]];sides.push({p:[q[a],q[b],this.p(...corners[b],nh),this.p(...corners[a],nh)],fill:dx?'#294b49':'#345854',bottom:nh});}
      const box={left:Infinity,right:-Infinity,top:Infinity,bottom:-Infinity};for(const points of [q,...sides.map(side=>side.p)])for(const p of points){if(p.x<box.left)box.left=p.x;if(p.x>box.right)box.right=p.x;if(p.y<box.top)box.top=p.y;if(p.y>box.bottom)box.bottom=p.y;}const tile={x,z,h,q,top,sides,noise,ramp:cell.ramp,protected:cell.protected,depth:this.depth(x+.5,z+.5),box};this.tiles.push(tile);}
    this.tiles.sort((a,b)=>a.depth-b.depth);for(const t of this.tiles){this.drawTile(ctx,t);const b=t.box;for(let bx=Math.floor(b.left/48);bx<=Math.floor(b.right/48);bx++)for(let by=Math.floor(b.top/48);by<=Math.floor(b.bottom/48);by++){const key=`${bx}:${by}`;if(!this.tileBuckets.has(key))this.tileBuckets.set(key,[]);this.tileBuckets.get(key).push(t);}}
    this.updatePaths();
    this.terrainRevision=state.terrain.revision??state.terrainRevision;this.dirty=false;
  }
  updatePaths(){const terrain=this.state.terrain,revision=terrain.revision??this.state.terrainRevision??0;if(this.pathTerrain===terrain&&this.pathRevision===revision)return;this.paths=Rules.entriesOf(this.state).map(entry=>({entry,path:Rules.pathToCore(this.state,entry.x,entry.z)}));this.pathTerrain=terrain;this.pathRevision=revision;}
  entryStatus(entry){const entries=(this.state?.phase==='battle'?this.state.battle?.entries:null)||this.encounter?.entries;if(!entries)return {...entry,active:false};const active=entries.find(e=>e.id===entry.id);return {...entry,...active,active:!!active};}
  drawTile(ctx,t){const scale=this.camera.scale;for(const side of t.sides){polygon(ctx,side.p,side.fill,this.fastTerrain?null:'#254642',.45);if(!this.fastTerrain&&scale>6&&t.noise>.45){const a=side.p[0],b=side.p[1],d=side.p[3];line(ctx,[{x:a.x*.7+b.x*.3,y:a.y*.7+b.y*.3+1},{x:a.x*.7+b.x*.3,y:d.y-1}],'#51746a',.5);}}polygon(ctx,t.q,t.top,this.fastTerrain?null:this.selection.terrainTool?'#5c81756b':'#8cad8c17',.5);
    if(!this.fastTerrain&&t.h===0&&scale>5&&t.noise>.65){const p=this.p(t.x+.24,t.z+.3,0);ctx.fillStyle='#6a927338';ctx.fillRect(Math.round(p.x),Math.round(p.y),Math.max(1,scale*.22),1);}
    if(!this.fastTerrain&&t.h>0&&scale>7&&t.noise>.76){const p=this.p(t.x+.5,t.z+.5,t.h);ctx.fillStyle='#b2c69b44';ctx.fillRect(Math.round(p.x),Math.round(p.y),1,1);}
    if(t.ramp!==null&&t.ramp!==undefined&&t.ramp!==false&&t.ramp!==-1){const dirs=typeof t.ramp==='string'?({north:[0,-1],south:[0,1],east:[1,0],west:[-1,0],n:[0,-1],s:[0,1],e:[1,0],w:[-1,0]})[t.ramp]:[[0,-1],[1,0],[0,1],[-1,0]][t.ramp];if(dirs){const [dx,dz]=dirs;for(let i=-1;i<=1;i++){const a=this.p(t.x+.5+dx*.22+i*dz*.17,t.z+.5+dz*.22-i*dx*.17,t.h+.02),b=this.p(t.x+.5-dx*.2+i*dz*.17,t.z+.5-dz*.2-i*dx*.17,t.h+.02);line(ctx,[a,b],COLORS.gold,.7);}}}
  }
  drawBackground(time){const ctx=this.ctx,w=this.camera.width,h=this.camera.height;ctx.fillStyle='#10272a';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#24403d55';ctx.lineWidth=1;for(let i=0;i<70;i++){const x=Math.floor(hash(i,4)*w),y=Math.floor(hash(i,88)*h);ctx.fillStyle=i%7===0?'#91b9a443':'#6c958b20';ctx.fillRect(x,y,1,1);}ctx.strokeRect(8.5,8.5,w-17,h-17);for(const x of [8,w-9])for(const y of [8,h-9]){ctx.fillStyle='#669586';ctx.fillRect(x-2,y-2,5,1);ctx.fillRect(x-2,y-2,1,5);}}
  drawRoutes(time){const ctx=this.ctx,preview=this.selection.terrainTool?this.selection.preview:null,routes=preview?.ok&&preview.paths?.length?preview.paths.map(route=>({entry:Rules.entriesOf(this.state).find(e=>e.id===route.entry),path:route.path})):this.paths;for(const {entry,path} of routes){if(!entry||!this.entryStatus(entry).active)continue;const points=path.map(p=>this.p(p.x+.5,p.z+.5,(preview?.cells?.find(c=>c.x===p.x&&c.z===p.z)?.h??this.heightAt(p.x,p.z))+.025));ctx.setLineDash([2,5]);ctx.lineDashOffset=-time*.003;line(ctx,points,preview?.ok?'#ead28cbb':'#ddc99568',1);ctx.setLineDash([]);for(const cell of path)if(cell.barrier){const p=this.p(cell.barrier.x+.5,cell.barrier.z+.5,this.heightAt(cell.barrier.x,cell.barrier.z)+.1);ctx.fillStyle=COLORS.coral;ctx.fillRect(Math.round(p.x)-1,Math.round(p.y)-3,2,4);ctx.fillRect(Math.round(p.x)-1,Math.round(p.y)+2,2,1);}}}
  drawCore(time){const core=Rules.coreOf(this.state),x=core.x+.5,z=core.z+.5,w=core.size||5,ctx=this.ctx,base=this.heightAt(x,z),pulse=(Math.sin(time*.002)+1)/2;
    polygon(ctx,this.quad(x-w/2,z-w/2,w,w,base+.04),'#32655b','#84c7a8',1);polygon(ctx,this.quad(x-w/2+.28,z-w/2+.28,w-.56,w-.56,base+.06),null,'#adc494',.6);
    for(const [dx,dz]of[[-1.5,-1.5],[1.5,-1.5],[-1.5,1.5],[1.5,1.5]])this.drawPylon(x+dx,z+dz,base,1.1,'#577f6c');
    const p=this.p(x,z,base+.4),radius=this.camera.scale*(1.45+pulse*.05);ctx.strokeStyle='#83e2be80';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(p.x,p.y,radius,radius*.43,0,0,TAU);ctx.stroke();
    const top=this.p(x,z,base+3.1+pulse*.08),left=this.p(x-.65,z,base+1.6),right=this.p(x+.65,z,base+1.6),back=this.p(x,z-.65,base+1.6),front=this.p(x,z+.65,base+1.6),bottom=this.p(x,z,base+.6);polygon(ctx,[top,left,front],'#8ce8be','#d1f4d5',.65);polygon(ctx,[top,front,right],'#54b6a3');polygon(ctx,[top,right,back],'#b8f1d0');polygon(ctx,[left,front,bottom],'#2e8e80');polygon(ctx,[front,right,bottom],'#4eae99');
    for(let i=0;i<6;i++){const phase=(time*.00016+i/6)%1,sp=this.p(x+Math.sin(i*2.4)*.7,z+Math.cos(i*2.4)*.7,base+.5+phase*3.6);ctx.fillStyle=`rgba(190,237,198,${(1-phase)*.7})`;ctx.fillRect(Math.round(sp.x),Math.round(sp.y),1,2);}
    const label=this.p(x,z,base);this.worldLabels.push({text:'火种',anchor:label,color:COLORS.mint,dx:0,dy:1});
  }
  drawPylon(x,z,h,height,color){const ctx=this.ctx,a=this.quad(x-.3,z-.3,.6,.6,h),b=this.quad(x-.3,z-.3,.6,.6,h+height);polygon(ctx,[a[3],a[2],b[2],b[3]],'#294c45');polygon(ctx,[a[1],a[2],b[2],b[1]],'#426b5b');polygon(ctx,b,color,'#9dc29b',.6);const p=this.p(x,z,h+height+.1);ctx.fillStyle=COLORS.gold;ctx.fillRect(Math.round(p.x)-1,Math.round(p.y)-1,3,1);}
  drawEntry(entry,time){const ctx=this.ctx,active=entry.active!==false&&entry.enabled!==false,x=entry.x+.5,z=entry.z+.5,h=this.heightAt(entry.x,entry.z),p=this.p(x,z,h),s=this.camera.scale,color=active?COLORS.coral:'#53766b';polygon(ctx,this.quad(x-1,z-1,2,2,h+.03),active?'#623e36':'#30443d',color,.8);for(let i=-1;i<=1;i++)line(ctx,[this.p(x-.7,z+i*.45,h+.04),this.p(x+.7,z+i*.45,h+.04)],active?'#e7907866':'#53766b',.6);
    this.drawPylon(x-1.1,z,h,1.3,active?'#c98970':'#517061');this.drawPylon(x+1.1,z,h,1.3,active?'#c98970':'#517061');
    const top=this.p(x,z,h+2.3);ctx.strokeStyle=color;ctx.lineWidth=1;ctx.strokeRect(Math.round(top.x)-3,Math.round(top.y)-3,6,6);if(active){ctx.fillStyle=color;ctx.fillRect(Math.round(top.x)-1,Math.round(top.y)-1,2,2);const r=((time*.0004)%1)*s*1.6;ctx.strokeStyle='#ed9b7740';ctx.beginPath();ctx.ellipse(p.x,p.y,r,r*.45,0,0,TAU);ctx.stroke();}
    const names={north:'北',south:'南',east:'东',west:'西',top:'北',bottom:'南',left:'西',right:'东'},core=Rules.coreOf(this.state),center=this.p(core.x+.5,core.z+.5,0),distance=Math.max(1,Math.hypot(p.x-center.x,p.y-center.y));this.worldLabels.push({text:`${active?'▲':'◇'} ${names[entry.id]||entry.name||entry.id}${active?` ${entry.count??'?'}`:''}`,anchor:p,color,dx:(p.x-center.x)/distance,dy:(p.y-center.y)/distance});
  }
  label(text,x,y,color=COLORS.ivory,size=12){const ctx=this.ctx;size=clamp(size,11,14);ctx.font=`${size}px Pixel, monospace`;ctx.textAlign='center';ctx.textBaseline='middle';const w=ctx.measureText(text).width;ctx.fillStyle='#10292ce8';ctx.fillRect(Math.round(x-w/2-4),Math.round(y-size/2-3),Math.ceil(w+8),size+6);ctx.fillStyle=color;ctx.fillText(text,Math.round(x),Math.round(y));}
  drawWorldLabels(){const ctx=this.ctx,occupied=[...this.entityBoxes,{left:this.camera.width-65,right:this.camera.width,top:0,bottom:65}],overlaps=(a,b)=>a.left<b.right+5&&a.right>b.left-5&&a.top<b.bottom+5&&a.bottom>b.top-5;ctx.font='12px Pixel, monospace';for(const item of this.worldLabels){const width=ctx.measureText(item.text).width+8,height=18;let placed=null;for(const distance of [24,42,64,88]){for(const [dx,dy]of [[item.dx,item.dy],[-item.dy,item.dx],[item.dy,-item.dx],[0,-1],[0,1]]){const x=clamp(item.anchor.x+dx*(distance+width*.35),width/2+12,this.camera.width-width/2-12),y=clamp(item.anchor.y+dy*(distance+height*.35),height/2+12,this.camera.height-height/2-12),box={left:x-width/2,right:x+width/2,top:y-height/2,bottom:y+height/2};if(!occupied.some(other=>overlaps(box,other))){placed={x,y,box};break;}}if(placed)break;}if(placed){line(ctx,[item.anchor,{x:placed.x,y:placed.y}],`${item.color}66`,1);this.label(item.text,placed.x,placed.y,item.color,12);occupied.push(placed.box);}}}
  drawSurgeTelegraphs(){
    const battle=this.state.battle;if(!battle)return;
    const radius=difficultyProfile(this.state).surge.range,ctx=this.ctx;
    for(const enemy of battle.enemies){
      if(enemy.dead||enemy.hp<=0||!(enemy.surgeWarningUntil>battle.time)||!enemy.surgeOrigin)continue;
      const origin=enemy.surgeOrigin,points=[];
      for(let i=0;i<=48;i++){const angle=i/48*TAU,x=origin.x+Math.cos(angle)*radius,z=origin.z+Math.sin(angle)*radius;points.push(this.p(x,z,this.heightAt(x,z)+.15));}
      ctx.setLineDash([7,4]);line(ctx,points,'#10252dec',5);line(ctx,points,COLORS.coral,2);ctx.setLineDash([]);
      const anchor=this.p(origin.x,origin.z,origin.h||0);
      this.worldLabels.push({text:`! 频震 · ${(enemy.surgeWarningUntil-battle.time).toFixed(1)}秒`,anchor,color:COLORS.coral,dx:0,dy:-1});
      for(const uid of enemy.surgeTargets||[]){const unit=this.state.units.find(u=>u.uid===uid);if(!unit||unit.hp<=0||!Rules.onField(unit))continue;const center=Rules.unitCenter(unit),target=this.p(center.x,center.z,this.heightAt(center.x,center.z)+.2);this.drawUnitOutline(unit,COLORS.coral);ctx.setLineDash([3,5]);line(ctx,[anchor,target],COLORS.coral,1.5);ctx.setLineDash([]);this.worldLabels.push({text:'! 频震锁定',anchor:target,color:COLORS.coral,dx:0,dy:1});}
    }
  }
  stats(unit){return Rules.unitStats(this.state,unit);}
  previewOrigin(){return this.hover||(!this.interactive?this.selection.previewOrigin:null)||null;}
  clearRange(){this.range=[];this.rangeBlocked=[];this.rangeEdges=[];this.rangeBlockedEdges=[];this.rangeSource=null;this.support=null;}
  updateRange(){const selected=this.selection.unit||this.state.units?.find(u=>u.uid===this.selection.selectedUid);if(!selected){this.clearRange();return;}const pos=this.selection.unit?this.previewOrigin():selected;if(!pos||pos.x==null||pos.z==null){this.clearRange();return;}const rev=this.state.terrain.revision??this.state.terrainRevision,stats=this.stats(selected),preview=this.selection.terrainTool?this.selection.preview:null,key=`${selected.uid}:${selected.type}:${selected.tier}:${selected.branch}:${pos.x}:${pos.z}:${selected.rotation||0}:${rev}:${stats.range}:${stats.targets}:${(this.state.relics||[]).join(',')}:${(this.state.talents||[]).join(',')}:${JSON.stringify(this.state.modifiers||{})}`;if(key===this.rangeKey&&preview===this.rangePreview)return;this.rangeKey=key;this.rangePreview=preview;this.clearRange();let source=this.state;const unit={...selected,x:pos.x,z:pos.z},n=this.state.terrain.size;
    if(preview?.ok&&preview.cells?.length){const terrain={...source.terrain,cells:source.terrain.cells.slice()};for(const c of preview.cells)terrain.cells[c.z*n+c.x]=c.after;source={...source,terrain};}
    // Obtain the largest possible radius from the same combat solver. Testing
    // only its bounding box avoids 1,681 expensive rule calls on every hover.
    const origin=Rules.unitCenter(unit),target={id:'preview',type:'static_drifter',hp:100,maxHp:100,air:stats.targets==='air',armor:0},radius=Rules.solveAttack(source,unit,{...target,...origin,h:0}).range;
    if(stats.role==='support'){
      this.support=Rules.supportCoverage(source,unit,{preview:!!this.selection.unit});
      for(let z=Math.max(0,Math.floor(origin.z-radius));z<=Math.min(n-1,Math.ceil(origin.z+radius));z++)for(let x=Math.max(0,Math.floor(origin.x-radius));x<=Math.min(n-1,Math.ceil(origin.x+radius));x++)if(Math.hypot(x-origin.x,z-origin.z)<=radius)this.range.push({x,z});
      this.rangeEdges=rangeBoundary(this.range);this.rangeSource=source;return;
    }
    for(let z=Math.max(0,Math.floor(origin.z-radius));z<=Math.min(n-1,Math.ceil(origin.z+radius));z++)for(let x=Math.max(0,Math.floor(origin.x-radius));x<=Math.min(n-1,Math.ceil(origin.x+radius));x++){const result=Rules.solveAttack(source,unit,{...target,x,z});if(result.ok)this.range.push({x,z});else if(result.blocked&&result.distance<=result.range)this.rangeBlocked.push({x,z});}this.rangeEdges=rangeBoundary(this.range);this.rangeBlockedEdges=rangeBoundary(this.rangeBlocked);this.rangeSource=source;
  }
  rangeHeight(cell){return Rules.cellAt(this.rangeSource||this.state,cell.x,cell.z)?.h||0;}
  drawRangeFill(){this.updateRange();for(const cell of this.range)polygon(this.ctx,this.quad(cell.x,cell.z,1,1,this.rangeHeight(cell)+.05),'#74ecc638',null);for(const cell of this.rangeBlocked){const h=this.rangeHeight(cell);polygon(this.ctx,this.quad(cell.x,cell.z,1,1,h+.05),'#ec987020',null);if((cell.x+cell.z)%2===0)line(this.ctx,[this.p(cell.x+.25,cell.z+.25,h+.06),this.p(cell.x+.75,cell.z+.75,h+.06)],'#edb28788',1);}}
  drawRangeEdges(edges,color,dashed=false){if(!edges.length)return;const ctx=this.ctx;ctx.beginPath();for(const edge of edges){const h=this.rangeHeight(edge)+.1,a=this.p(edge.x+edge.a[0],edge.z+edge.a[1],h),b=this.p(edge.x+edge.b[0],edge.z+edge.b[1],h);ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);}ctx.setLineDash(dashed?[5,4]:[]);ctx.lineWidth=4;ctx.strokeStyle='#0b222ae8';ctx.stroke();ctx.lineWidth=dashed?1.5:2;ctx.strokeStyle=color;ctx.stroke();ctx.setLineDash([]);}
  drawUnitOutline(unit,color){const g=this.entityGeometry(unit),p=this.p(g.x,g.z,g.h),size=this.modelSize(unit,g),box=this.modelBox(p,size,ENTITY_ART[unit.type]),left=box.left-3,right=box.right+3,top=box.top-3,bottom=box.bottom+3,l=clamp((right-left)*.2,6,12);for(const [x,y,dx,dy]of [[left,top,1,1],[right,top,-1,1],[left,bottom,1,-1],[right,bottom,-1,-1]]){const points=[{x:x+dx*l,y},{x,y},{x,y:y+dy*l}];line(this.ctx,points,'#10292c',4);line(this.ctx,points,color,2);}}
  drawSelection(){const ctx=this.ctx,sel=this.selection,origin=this.previewOrigin();this.updateRange();this.drawRangeEdges(this.rangeBlockedEdges,'#f1b586',true);this.drawRangeEdges(this.rangeEdges,'#a7ffe2');if(this.support){const unit=sel.unit?{...sel.unit,...origin}:this.state.units.find(u=>u.uid===sel.selectedUid);if(unit&&unit.x!=null){this.support=Rules.supportCoverage(this.state,unit,{preview:!!sel.unit});for(const ally of this.support.affected){this.drawUnitOutline(ally,COLORS.mint);const p=this.entityGeometry(ally);polygon(ctx,this.quad(ally.x,ally.z,...p.fp,p.h+.13),'#79dfc136',COLORS.mint,2);}}}
    const selected=this.state.units?.find(u=>u.uid===sel.selectedUid);if(selected&&selected.x!=null&&!sel.unit){const stats=this.stats(selected);polygon(ctx,this.quad(selected.x,selected.z,...stats.footprint,this.heightAt(selected.x,selected.z)+.12),null,'#122b28',5);polygon(ctx,this.quad(selected.x,selected.z,...stats.footprint,this.heightAt(selected.x,selected.z)+.12),null,COLORS.gold,2.5);this.drawUnitOutline(selected,COLORS.gold);}
    if(!origin)return;let footprint=[origin],verdict=sel.preview;if(sel.unit){footprint=Rules.footprint(this.state,sel.unit,origin.x,origin.z);verdict=verdict||Rules.placement(this.state,sel.unit,origin.x,origin.z);}else if(sel.terrainTool){const command={tool:sel.terrainTool,brush:sel.brush||'single',x:origin.x,z:origin.z,direction:sel.direction??0};verdict=verdict||Rules.previewTerrain(this.state,command);const changes=verdict?.changes||verdict?.cells;if(changes?.length)footprint=changes;}
    const ok=!verdict||verdict.ok||verdict.valid,color=ok?COLORS.mint:COLORS.coral;for(const cell of footprint){if(cell.x<0||cell.z<0||cell.x>=this.state.terrain.size||cell.z>=this.state.terrain.size)continue;const h=this.heightAt(cell.x,cell.z);polygon(ctx,this.quad(cell.x,cell.z,1,1,h+.07),ok?'#9ce6b340':'#f37c7455','#10292c',4);polygon(ctx,this.quad(cell.x,cell.z,1,1,h+.08),null,color,1.8);const next=cell.h??cell.after?.h??cell.to?.h;if(sel.terrainTool&&Number.isFinite(next)&&next!==h)polygon(ctx,this.quad(cell.x,cell.z,1,1,next+.08),'#e9d69344',COLORS.gold,2);if(!ok){const q=this.quad(cell.x+.2,cell.z+.2,.6,.6,h+.1);line(ctx,[q[0],q[2]],color,1.8);line(ctx,[q[1],q[3]],color,1.8);}}
    if(sel.unit){const ghost={...sel.unit,x:origin.x,z:origin.z};this.drawUnit(ghost,performance.now(),true);this.drawUnitOutline(ghost,color);}
    // Coordinates, bandwidth, costs and failure reasons belong in the fixed DOM
    // placement status. Keeping them off the pointer avoids covering the ghost.
  }
  entityGeometry(entity,enemy=false){const stats=enemy?null:this.stats(entity),fp=stats?.footprint||[1,1],center=enemy?entity:Rules.unitCenter(entity),x=center.x+.5,z=center.z+.5,h=(enemy&&Number.isFinite(entity.h)?entity.h:this.heightAt(entity.x,entity.z))+(enemy&&entity.air?1.3:0);return {x,z,h,fp,stats,depth:this.depth(x,z)};}
  modelSize(entity,g,enemy=false){const art=ENTITY_ART[entity.type],boss=entity.kind==='boss'||entity.boss,elite=entity.kind==='elite'||entity.elite,world=enemy?(boss?5.1:elite?3.4:2.65):Math.max(...g.fp)*1.05+1.25,minimum=enemy?(boss?38:elite?26:20):28,extent=enemy&&art?.minVisibleSpan?art.minVisibleSpan:Math.max(art?.bounds?.width||80,art?.bounds?.height||80);return Math.max(this.camera.scale*world*1.5,minimum*(art?.cell||80)/extent);}
  modelBox(p,size,art){const b=art?.bounds||{x:0,y:0,width:80,height:80},cell=art?.cell||80,baseline=art?.baseline||.72;return {left:p.x-size/2+b.x/cell*size,right:p.x-size/2+(b.x+b.width)/cell*size,top:p.y-size*baseline+b.y/cell*size,bottom:p.y-size*baseline+(b.y+b.height)/cell*size};}
  drawModel(type,pose,p,size,{opacity=1,wreck=false}={}){
    const art=ENTITY_ART[type],img=this.images.get(type);if(!art||!img?.complete||!img.naturalWidth){this.label('…',p.x,p.y-5,COLORS.mint,9);return;}
    const ctx=this.ctx,frame=directionFrame(Math.sin(pose.facing),Math.cos(pose.facing),this.camera.yaw,art.bearing),drawSize=size*(1-pose.spawn*.18),height=drawSize*(wreck?.6:1),shake=pose.hit>0?Math.round(Math.sin(pose.hit*19)*pose.hit*1.5):0;
    const x=Math.round(p.x-drawSize/2)+shake,y=Math.round(p.y-height*art.baseline),width=Math.round(drawSize),h=Math.round(height);
    ctx.save();ctx.globalAlpha*=opacity*(1-pose.spawn*.65);ctx.drawImage(img,frame*art.cell,pose.row*art.cell,art.cell,art.cell,x,y,width,h);
    if(pose.hit>.05){ctx.globalCompositeOperation='screen';ctx.globalAlpha*=pose.hit*.7;ctx.drawImage(img,frame*art.cell,pose.row*art.cell,art.cell,art.cell,x,y,width,h);}
    ctx.restore();this.entityFrames.push({...pose,type,direction:frame,x:p.x,y:p.y,size:drawSize});
  }
  drawUnit(unit,time,ghost=false){if(unit.x==null||unit.z==null)return;const g=this.entityGeometry(unit),ctx=this.ctx,p=this.p(g.x,g.z,g.h),s=this.camera.scale,selected=this.selection.selectedUid===unit.uid,size=this.modelSize(unit,g),art=ENTITY_ART[unit.type],box=this.modelBox(p,size,art),pose=this.entityMotion.sample(unit,'unit',{reducedMotion:this.selection.reducedMotion,ghost,variants:art?.variants});if(ghost||this.state.phase==='prep'||unit.lastActionAt==null)pose.facing=(unit.rotation||0)*Math.PI/2;ctx.save();
    polygon(ctx,this.quad(unit.x,unit.z,g.fp[0],g.fp[1],g.h+.06),selected?'#78d7ad55':'#193c3644',selected?COLORS.gold:'#8cbfa56b',selected?1:.6);ctx.fillStyle='#0b252666';ctx.beginPath();ctx.ellipse(p.x,p.y+1,s*Math.max(...g.fp)*.44,s*.32,0,0,TAU);ctx.fill();
    this.drawModel(unit.type,pose,p,size,{opacity:ghost?.6:unit.hp<=0?.38:pose.action==='disabled'?.43:1,wreck:unit.hp<=0});
    ctx.restore();this.entityBoxes.push(box);if(!ghost){if(unit.hp<g.stats.hp||selected||pose.action==='disabled')this.bar(p.x,box.bottom+3,Math.max(26,s*g.fp[0]),unit.hp/g.stats.hp,COLORS.mint);if(pose.action==='disabled')this.label('Ⅱ 停机',p.x,box.top-7,COLORS.gold,11);else if(unit.hp<=0)this.label('× 待维修',p.x,box.top-7,COLORS.coral,11);else if((unit.tier||1)>1){ctx.fillStyle=unit.branch==='B'?COLORS.ivory:COLORS.gold;for(let i=0;i<unit.tier-1;i++)ctx.fillRect(Math.round(p.x+(i-(unit.tier-2)/2)*5)-1,Math.round(box.top)-5,3,3);}this.occlude(g,p,size);}
  }
  drawEnemy(enemy,time){if(enemy.hp<=0||enemy.dead)return;const g=this.entityGeometry(enemy,true),ctx=this.ctx,p=this.p(g.x,g.z,g.h),s=this.camera.scale,boss=enemy.kind==='boss'||enemy.boss,elite=enemy.kind==='elite'||enemy.elite,size=this.modelSize(enemy,g,true),art=ENTITY_ART[enemy.type],box=this.modelBox(p,size,art),pose=this.entityMotion.sample(enemy,'enemy',{reducedMotion:this.selection.reducedMotion,variants:art?.variants});
    ctx.fillStyle='#16282580';ctx.beginPath();ctx.ellipse(p.x,p.y+s*.1,size*.23,size*.09,0,0,TAU);ctx.fill();this.drawModel(enemy.type,pose,p,size);
    this.entityBoxes.push(box);this.bar(p.x,box.top-6,Math.max(20,(box.right-box.left)*.8),enemy.hp/enemy.maxHp,COLORS.coral);if(boss)this.label(`◆ 首领 · ${['Ⅰ','Ⅱ','Ⅲ'][clamp(enemy.phase||0,0,2)]}`,p.x,box.top-17,COLORS.gold);if(enemy.pressureMarked){const x=box.left-4,y=box.top-4;polygon(ctx,[{x,y:y-3},{x:x+3,y},{x,y:y+3},{x:x-3,y}],COLORS.gold,'#10292c',.8);ctx.fillStyle='#10292c';ctx.fillRect(Math.round(x),Math.round(y)-1,1,2);if(!this.selection.reducedMotion&&Math.sin(time*.006)>0){ctx.strokeStyle=COLORS.gold;ctx.strokeRect(Math.round(x)-4,Math.round(y)-4,8,8);}if(this.hover&&Math.hypot(enemy.x-this.hover.x,enemy.z-this.hover.z)<1.2)this.label('! 高压力目标',p.x,box.top-17,COLORS.gold);}
    if(enemy.shield>0){ctx.strokeStyle='#d8c48d';ctx.beginPath();ctx.ellipse(p.x,p.y-size*.28,size*.37,size*.36,0,0,TAU);ctx.stroke();}if((Number.isFinite(enemy.castUntil)?enemy.castUntil:enemy.warningUntil)>(this.state.battle?.time??0)||enemy.telegraph||enemy.casting){const r=size*.52;ctx.setLineDash([2,2]);ctx.strokeStyle=COLORS.coral;ctx.beginPath();ctx.ellipse(p.x,p.y,r,r*.45,0,0,TAU);ctx.stroke();ctx.setLineDash([]);this.label('! 能力蓄力',p.x,box.top-(boss?31:17),COLORS.gold,9);}this.occlude(g,p,size);
  }
  drawDeath(death){const enemy=death.entity,art=ENTITY_ART[enemy.type];if(!art)return;const age=clamp((this.entityMotion.clock-death.at)/650,0,1),g=this.entityGeometry(enemy,true),p=this.p(g.x,g.z,g.h),size=this.modelSize(enemy,g,true),pose=this.entityMotion.sample({...enemy,hp:0},'enemy',{variants:art.variants,reducedMotion:true});
    this.ctx.save();const collapsed=this.selection.reducedMotion?size:size*(1-age*.32);this.drawModel(enemy.type,{...pose,action:'death',progress:age},p,collapsed,{opacity:(1-age)*.65,wreck:true});this.ctx.restore();this.occlude(g,p,size);
  }
  occluders(g,p,size){
    const candidates=new Set();for(let bx=Math.floor((p.x-size/2)/48);bx<=Math.floor((p.x+size/2)/48);bx++)for(let by=Math.floor((p.y-size)/48);by<=Math.floor((p.y+size*.2)/48);by++)for(const tile of this.tileBuckets.get(`${bx}:${by}`)||[])if(tile.depth>g.depth+.45&&tile.h>g.h+.4&&tile.box.right>p.x-size/2&&tile.box.left<p.x+size/2&&tile.box.bottom>p.y-size&&tile.box.top<p.y+size*.2)candidates.add(tile);
    return candidates;
  }
  occlude(g,p,size){
    // Each foreground polygon erases only this entity's private layer. All
    // previously composed terrain and entities keep their painter order.
    if(!this.maskingEntity)return;
    this.ctx.save();this.ctx.globalCompositeOperation='destination-out';
    for(const tile of this.occlusionTiles){for(const side of tile.sides)polygon(this.ctx,side.p,'#000',null);polygon(this.ctx,tile.q,'#000',null);}
    this.ctx.restore();
  }
  drawEntityItem(item){
    const entity=item.kind==='death'?item.value.entity:item.value,enemy=item.kind!=='unit',g=this.entityGeometry(entity,enemy),p=this.p(g.x,g.z,g.h),size=this.modelSize(entity,g,enemy);
    const draw=()=>{if(item.kind==='unit')this.drawUnit(entity,this.entityMotion.clock);else if(item.kind==='death')this.drawDeath(item.value);else this.drawEnemy(entity,this.entityMotion.clock);};
    this.occlusionTiles=this.occluders(g,p,size);if(!this.occlusionTiles.size){draw();return;}
    const main=this.ctx,layer=this.entityLayer||=makeCanvas(),rx=this.canvas.width/this.camera.width,ry=this.canvas.height/this.camera.height;
    const x=Math.max(0,Math.floor(p.x-size)),y=Math.max(0,Math.floor(p.y-size*1.6)),w=Math.min(this.camera.width-x,Math.ceil(size*2)),h=Math.min(this.camera.height-y,Math.ceil(size*2.2));if(w<=0||h<=0)return;
    const pw=Math.ceil(w*rx),ph=Math.ceil(h*ry);if(layer.width<pw)layer.width=Math.ceil(pw/64)*64;if(layer.height<ph)layer.height=Math.ceil(ph/64)*64;const ctx=layer.getContext('2d');ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,pw,ph);ctx.setTransform(rx,0,0,ry,-x*rx,-y*ry);ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.imageSmoothingEnabled=false;
    this.ctx=ctx;this.maskingEntity=true;try{draw();}finally{this.maskingEntity=false;this.ctx=main;ctx.restore();}
    main.drawImage(layer,0,0,w*rx,h*ry,x,y,w,h);
  }
  bar(x,y,width,value,color){const ctx=this.ctx,w=Math.round(width),left=Math.round(x-w/2),top=Math.round(y);ctx.fillStyle='#122e2be8';ctx.fillRect(left-1,top-1,w+2,6);ctx.fillStyle='#59766a';ctx.fillRect(left,top,w,4);ctx.fillStyle=color;ctx.fillRect(left,top,Math.round(w*clamp(value||0,0,1)),4);}
  consumeEvents(events,time){for(const event of events){
    const type=event.action==='spawn'?'spawn':event.action==='death'?'death':event.action==='phase'?'boss_phase':event.action==='breach'?'breakthrough':({hit:'enemy_attack',terrain:'terrain_break',warning:'ability',boss:'ability'})[event.type]||event.type;
    if(!['shot','attack','unit_attack','enemy_attack','death','pressure','explosion','heal','repair','spawn','terrain_break','breakthrough','boss_phase','ability','support'].includes(type))continue;
    if(event.ability==='surge'&&event.stage==='windup')continue; // Dedicated world-space lock and countdown.
    const start=Number.isFinite(event.time)?event.time*1000:time,duration=event.stage==='windup'?Math.max(50,(event.duration||.4)*1000):type==='shot'||type==='enemy_attack'?260:type==='support'?420:type==='boss_phase'?700:500;
    this.effects.push({...event,type,from:event.from||(Number.isFinite(event.tx)?{x:event.x,z:event.z}:event.unit),to:event.to||(Number.isFinite(event.tx)?{x:event.tx,z:event.tz}:event.target),damage:event.damage||event.amount,start,duration});
  }if(this.effects.length>180)this.effects.splice(0,this.effects.length-180);}
  eventPoint(value,fallback,kind,type){const air=kind==='enemy'&&enemies[type]?.air?1.3:0;if(value&&Number.isFinite(value.x)&&Number.isFinite(value.z))return this.p(value.x+.5,value.z+.5,(value.h??this.heightAt(value.x,value.z))+.8+air);const id=typeof value==='object'?(value?.uid??value?.id):value,entity=this.state.units?.find(u=>u.uid===id)||this.state.battle?.enemies?.find(e=>e.id===id);if(entity){const g=this.entityGeometry(entity,!!entity.maxHp);return this.p(g.x,g.z,g.h+.8);}if(fallback&&Number.isFinite(fallback.x))return this.p(fallback.x+.5,fallback.z+.5,this.heightAt(fallback.x,fallback.z)+.3+air);return null;}
  drawEffects(time){const ctx=this.ctx,reduced=!!this.selection.reducedMotion;this.effects=this.effects.filter(e=>time>=e.start&&time-e.start<e.duration);for(const e of this.effects){
    const age=clamp((time-e.start)/e.duration,0,1),origin=this.eventPoint(e.from||e.sourceId||e.unit,e,e.sourceKind,e.sourceType),target=this.eventPoint(e.to||e.targetId||e.target,null,e.targetKind,e.targetType),p=origin||this.eventPoint(e.position||e.at||e.enemy,e,e.sourceKind,e.sourceType);ctx.save();ctx.globalAlpha=(1-age)*(e.type==='support'?.55:1);
    if(['shot','attack','unit_attack','enemy_attack'].includes(e.type)&&origin&&target){
      const color=e.type==='enemy_attack'?COLORS.coral:COLORS.gold,kind=e.actionKind||e.kind,dx=target.x-origin.x,dy=target.y-origin.y;
      if(kind==='melee'){
        const r=clamp(this.camera.scale*.55,5,17);ctx.strokeStyle=color;ctx.lineWidth=2.2;ctx.beginPath();ctx.moveTo(target.x-r,target.y-r*.3);ctx.quadraticCurveTo(target.x+r*.7,target.y-r*1.4,target.x+r,target.y+r*.45);ctx.stroke();
      }else if(kind==='indirect'){
        const lift=Math.max(10,Math.hypot(dx,dy)*.23);ctx.strokeStyle=color;ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(origin.x,origin.y);ctx.quadraticCurveTo((origin.x+target.x)/2,(origin.y+target.y)/2-lift,target.x,target.y);ctx.stroke();
        if(!reduced){ctx.strokeStyle=COLORS.coral;ctx.beginPath();ctx.ellipse(target.x,target.y,4+age*12,2+age*6,0,0,TAU);ctx.stroke();}
      }else if(kind==='drone'){
        ctx.setLineDash([3,4]);line(ctx,[origin,target],COLORS.mint,1.3);ctx.setLineDash([]);const x=target.x-dx*.2,y=target.y-dy*.2;polygon(ctx,[{x:x-4,y},{x,y:y-3},{x:x+4,y},{x,y:y+3}],COLORS.ivory,COLORS.mint,1);
      }else if(kind==='chain'){
        const normal={x:-dy*.07,y:dx*.07};line(ctx,[origin,{x:origin.x+dx*.32+normal.x,y:origin.y+dy*.32+normal.y},{x:origin.x+dx*.63-normal.x,y:origin.y+dy*.63-normal.y},target],COLORS.mint,1.6);
      }else {line(ctx,[origin,target],color,e.sourceType==='focus_rail'?2.6:1.6);if(e.sourceType==='focus_rail')line(ctx,[origin,target],COLORS.ivory,.85);}
      ctx.fillStyle=COLORS.ivory;ctx.fillRect(Math.round(target.x)-2,Math.round(target.y)-2,4,4);
    }else if((e.type==='heal'||e.type==='repair')&&origin&&target){
      ctx.strokeStyle=COLORS.mint;ctx.lineWidth=1.6;ctx.beginPath();ctx.moveTo(origin.x,origin.y);ctx.quadraticCurveTo((origin.x+target.x)/2,(origin.y+target.y)/2-10,target.x,target.y);ctx.stroke();ctx.fillStyle=COLORS.mint;ctx.fillRect(Math.round(target.x)-1,Math.round(target.y)-4,2,8);ctx.fillRect(Math.round(target.x)-4,Math.round(target.y)-1,8,2);
    }else if(p){
      const progress=reduced?0:age,color=e.type==='heal'||e.type==='repair'||e.type==='support'?COLORS.mint:e.type==='pressure'||e.type==='boss_phase'?COLORS.gold:COLORS.coral,r=this.camera.scale*(.4+progress*(e.type==='pressure'?5:1.8));
      ctx.strokeStyle=color;ctx.lineWidth=e.type==='boss_phase'?2:1;ctx.beginPath();ctx.ellipse(p.x,p.y,r,r*.5,0,0,TAU);ctx.stroke();
      if(!reduced&&e.stage!=='windup')for(let i=0;i<(e.type==='support'?3:5);i++){const a=i*TAU/5,px=p.x+Math.cos(a)*r,py=p.y+Math.sin(a)*r*.5-age*8;ctx.fillStyle=color;ctx.fillRect(Math.round(px),Math.round(py),2,2);}
      if(e.damage>0&&e.type!=='death')this.label(`${e.type==='heal'?'+':'−'}${Math.ceil(e.damage)}`,p.x,p.y-(reduced?4:age*16),color,9);
    }ctx.restore();
  }}
  drawCompass(){const ctx=this.ctx,x=this.camera.width-33,y=33,r=16;ctx.fillStyle='#10292ceb';ctx.beginPath();ctx.arc(x,y+2,28,0,TAU);ctx.fill();ctx.strokeStyle='#517b68';ctx.stroke();ctx.font='11px Pixel, monospace';ctx.textAlign='center';ctx.textBaseline='middle';for(const [name,dx,dz]of[['北',0,-1],['南',0,1],['西',-1,0],['东',1,0]]){const c=Math.cos(this.camera.yaw),s=Math.sin(this.camera.yaw),px=x+(dx*c-dz*s)*r,py=y+(dx*s+dz*c)*r*S;ctx.fillStyle=name==='北'?COLORS.gold:'#8cb5a1';ctx.fillText(name,Math.round(px),Math.round(py));}ctx.fillStyle=COLORS.mint;ctx.fillRect(x-1,y-1,3,3);ctx.fillStyle='#9bb7a4';ctx.fillText(`${Math.round(wrapAngle(this.camera.yaw)*180/Math.PI)}°`,x,y+23);}
  render(time=performance.now(),events=[]){
    const state=this.state;if(!state)return this.renderFrame(time,events);
    // Read-only, synchronous drawing shares one rules cache and always drops it.
    Rules.beginRulesFrame(state);try{return this.renderFrame(time,events);}finally{Rules.endRulesFrame(state);}
  }
  renderFrame(time,events){const delta=clamp((time-this.lastTime)/1000,0,.05);this.lastTime=time;const moving=this.interactive&&cameraStep(this.camera,this.keys,delta);if(moving){this.dirty=true;this.updateHover();}if(this.fastTerrain!==moving){this.fastTerrain=moving;this.dirty=true;}const visualTime=this.selection.reducedMotion?0:time;this.drawBackground(visualTime);if(!this.state?.terrain)return;
    const rev=this.state.terrain.revision??this.state.terrainRevision;if(this.dirty||rev!==this.terrainRevision){this.buildTerrain();this.updateHover();}this.entityMotion.update(this.state,events,time);this.entityFrames=[];this.consumeEvents(events,this.entityMotion.clock);this.worldLabels=[];this.entityBoxes=[];this.ctx.drawImage(this.cache,0,0,this.camera.width,this.camera.height);if(this.state.phase!=='battle'||this.selection.terrainTool)this.drawRoutes(visualTime);this.drawRangeFill();
    const core=Rules.coreOf(this.state),items=[{depth:this.depth(core.x+.5,core.z+.5),kind:'core'}];for(const e of Rules.entriesOf(this.state))items.push({depth:this.depth(e.x+.5,e.z+.5),kind:'entry',value:this.entryStatus(e)});for(const u of this.state.units||[])if(u.x!=null&&u.z!=null){const g=this.entityGeometry(u);items.push({depth:g.depth,kind:'unit',value:u});}for(const e of this.state.battle?.enemies||[])items.push({depth:this.depth(e.x+.5,e.z+.5),kind:'enemy',value:e});for(const death of this.entityMotion.deaths)items.push({depth:this.depth(death.entity.x+.5,death.entity.z+.5),kind:'death',value:death});items.sort((a,b)=>a.depth-b.depth);for(const item of items){if(item.kind==='core')this.drawCore(visualTime);else if(item.kind==='entry')this.drawEntry(item.value,visualTime);else this.drawEntityItem(item);}
    this.drawEffects(this.entityMotion.clock);this.drawSelection();this.drawSurgeTelegraphs();this.drawWorldLabels();this.drawCompass();if(this.errors.length)this.label(this.errors[0],this.camera.width/2,20,COLORS.coral,12);
  }
  destroy(){for(const remove of this.listeners)remove();this.observer.disconnect();this.keys.clear();this.effects=[];this.images.clear();this.entityMotion.reset();this.entityFrames=[];}
}
import {difficultyProfile} from '../core/difficulty.js';
