async (page) => {
 const results=[],errors=[];page.setDefaultTimeout(8000);page.on('pageerror',error=>errors.push(error.message));
 const check=(condition,message)=>{if(!condition)throw new Error(message);results.push(message);};
 const click=action=>page.locator(`[data-action="${action}"]`).first().click();
 const approve=()=>page.locator('.modal-footer .primary').click();
 const cancel=()=>page.locator('[data-modal="close"]').click();
 await page.setViewportSize({width:1366,height:768});
 await page.goto('http://127.0.0.1:4175/?qa=1');
 await page.waitForFunction(()=>!!window.__mindrealm);
 await click('new');await page.locator('#seed-input').fill('reference-0');await approve();
 check(await page.locator('.map-node.available').count()===4,'开局四个战斗节点');
 await click('enter');
 const opening=await page.evaluate(()=>window.__mindrealm.getState());
 check(opening.phase==='prep'&&opening.focus===99&&opening.units.every(u=>u.x===null),'开局战前与资源');
 await page.locator('[data-action="select-unit"][data-uid="u4"]').click();
 const core=await page.evaluate(()=>{const q=window.__mindrealm,r=document.querySelector('canvas').getBoundingClientRect(),p=q.field.project(20.5,24.5,0);return{x:p.x+r.x,y:p.y+r.y};});
 await page.mouse.click(core.x,core.y);
 check(await page.evaluate(()=>window.__mindrealm.getState().units.find(u=>u.uid==='u4').x===null&&window.__mindrealm.getState().focus===99),'保护区非法部署不扣费');
 await page.keyboard.press('Escape');
 check(await page.evaluate(()=>window.__mindrealm.getContext().deployUid===null),'Esc取消部署');
 const legal=await page.evaluate(async()=>{const R=await import('/web/core/rules.js'),q=window.__mindrealm,s=q.getState(),u=s.units.find(u=>u.uid==='u4');let choices=[];for(let z=12;z<24;z++)for(let x=12;x<30;x++)if(R.placement(s,u,x,z).ok)choices.push({x,z,d:Math.hypot(x-20,z-18)});choices.sort((a,b)=>a.d-b.d);return choices[0];});
 await page.locator('[data-action="select-unit"][data-uid="u4"]').click();
 const point=await page.evaluate(cell=>{const q=window.__mindrealm,s=q.getState(),r=document.querySelector('canvas').getBoundingClientRect(),p=q.field.project(cell.x+.5,cell.z+.5,s.terrain.cells[cell.z*41+cell.x].h);return{x:p.x+r.x,y:p.y+r.y};},legal);
 await page.mouse.move(point.x,point.y);await page.mouse.click(point.x,point.y);
 check(await page.evaluate(cell=>{const s=window.__mindrealm.getState(),u=s.units.find(u=>u.uid==='u4');return u.x===cell.x&&u.z===cell.z&&s.focus===99;},legal),'鼠标合法部署与首次免费');
 await page.screenshot({path:'battle-deployment.png'});
 await click('move');await page.keyboard.press('Escape');
 check(await page.evaluate(cell=>{const s=window.__mindrealm.getState(),u=s.units.find(u=>u.uid==='u4');return u.x===cell.x&&u.z===cell.z&&s.focus===99;},legal),'取消搬迁保留位置与费用');
 await click('tab-terrain');
 const terrain=await page.evaluate(async()=>{const R=await import('/web/core/rules.js'),q=window.__mindrealm,s=q.getState();const cell={x:18,z:16};const p=R.previewTerrain(s,{...cell,tool:'raise',brush:'single'}),r=document.querySelector('canvas').getBoundingClientRect(),screen=q.field.project(cell.x+.5,cell.z+.5,s.terrain.cells[cell.z*41+cell.x].h);return{cell,before:s.terrain.cells[cell.z*41+cell.x].h,p,point:{x:screen.x+r.x,y:screen.y+r.y}};});
 check(terrain.p.ok,'地形测试点合法');
 await page.mouse.click(terrain.point.x,terrain.point.y);await cancel();
 check(await page.evaluate(()=>window.__mindrealm.getState().focus===99),'取消地形预览不扣费');
 await page.mouse.click(terrain.point.x,terrain.point.y);await approve();
 check(await page.evaluate(()=>window.__mindrealm.getState().focus===97),'地形确认按实际格扣费');
 await click('undo');
 check(await page.evaluate(t=>{const s=window.__mindrealm.getState();return s.focus===99&&s.terrain.cells[t.cell.z*41+t.cell.x].h===t.before;},terrain),'撤销地形原额退款');
 await click('tab-units');
 await page.evaluate(async()=>{const helper=await import('/development/web-tests/helpers/reference-strategy.mjs');helper.prepareReference(window.__mindrealm.getState());window.__mindrealm.render();});
 const before=await page.evaluate(()=>window.__mindrealm.getState());
 await click('start');await cancel();
 check(await page.evaluate(()=>window.__mindrealm.getState().phase==='prep'),'取消开战保持战前');
 await click('start');await approve();
 await page.evaluate(()=>window.__mindrealm.advance(8));
 await click('pause');
 const firstTime=await page.evaluate(()=>window.__mindrealm.getState().battle.time);
 await page.waitForTimeout(180);
 check(await page.evaluate(t=>window.__mindrealm.getState().battle.time===t,firstTime),'战斗暂停停止模拟');
 check(await page.locator('[data-action="tab-terrain"]').isDisabled(),'战斗中禁止改造');
 await page.screenshot({path:'battle-first-wave.png'});
 await click('menu');await approve();await click('continue');
 check(await page.evaluate(s=>{const now=window.__mindrealm.getState();return now.phase==='prep'&&now.focus===s.focus&&JSON.stringify(now.units.map(u=>[u.uid,u.x,u.z,u.hp,u.tier]))===JSON.stringify(s.units.map(u=>[u.uid,u.x,u.z,u.hp,u.tier]));},before),'战中退出继续还原战前全部部署耐久');
 await click('start');await approve();await page.evaluate(()=>window.__mindrealm.advance(300));
 check(await page.evaluate(()=>window.__mindrealm.getState().phase==='reward'),'真实首战进入奖励');
 await page.screenshot({path:'first-reward.png'});
 const offers=await page.evaluate(()=>window.__mindrealm.getState().rewardQueue);
 await click('menu');await click('continue');
 check(await page.evaluate(offers=>JSON.stringify(window.__mindrealm.getState().rewardQueue)===JSON.stringify(offers),offers),'奖励退出继续候选不刷新');
 while(await page.locator('[data-action="reward"]').count())await click('reward');
 check(await page.evaluate(()=>window.__mindrealm.getState().phase==='map'),'全部奖励处理后返回路线');
 await click('menu');await click('new');await cancel();
 check(await page.evaluate(()=>window.__mindrealm.getState().stats.completedNodes===1),'取消新开局保留进度');
 await click('continue');await click('settings');
 for(const scale of ['1','1.25','1.5']){await page.locator('[data-action="ui-scale"]').selectOption(scale);await page.screenshot({path:`settings-scale-${scale}.png`});}
 await page.locator('[data-action="ui-scale"]').selectOption('1');
 await click('back');
 check(errors.length===0,`浏览器无脚本错误 ${errors.join(';')}`);
 return {status:'MINDREALM_BROWSER_FLOW_OK',checks:results,errors};
}
