import {events,acts,towers} from './core/content.js';
import {eventStories,eventArtPath} from './core/event-stories.js';
import {eventPreview} from './core/state.js';
import {inventoryStatus,items} from './core/inventory.js';
import {escapeHTML as e,icon} from './ui.js';

export function eventScene(state,hud){
 const data=state.currentNode.eventData,event=events[data.id],story=eventStories[data.id],outcome=data.outcome,branch=outcome&&story.choices[outcome.index],bag=inventoryStatus(state);
 const options=outcome?`<article class="event-outcome"><div class="event-option-label">选择已经生效</div><h3>${e(branch.title)}</h3><div class="event-result">${outcome.details.map(e).join('<br>')}</div><button class="event-choice-button event-continue" data-action="event-continue"><strong>${state.rewardQueue.length?'查看获得的奖励':'继续前进'}</strong>${icon('arrow')}</button></article>`:event.choices.map((choice,index)=>{
  const preview=eventPreview(state,index),fx=choice.effects;
  return `<article class="event-choice ${preview.canChoose?'':'unavailable'}" data-event-card="${index}"><div class="event-option-label">选择 0${index+1}</div>${fx.recycle?`<label class="event-material">回收库存构造<select data-event-unit="${index}" aria-label="选择回收的库存构造">${bag.stored.map(u=>`<option value="${u.uid}" ${u.uid===preview.recycleUid?'selected':''}>${e(towers[u.type].name)} T${u.tier}${u.branch||''} · ${u.uid}</option>`).join('')||'<option value="">没有可回收的库存构造</option>'}</select></label>`:''}${fx.consume_item?`<label class="event-material">交出的道具<select data-event-item="${index}" aria-label="选择交出的道具">${bag.items.map(item=>`<option value="${item.uid}" ${item.uid===preview.itemUid?'selected':''}>${e(items[item.type].name)}</option>`).join('')||'<option value="">没有可交换的道具</option>'}</select></label>`:''}<button class="event-choice-button" data-action="event-choice" data-index="${index}" ${preview.canChoose?'':'disabled'}><strong>${e(story.choices[index].label)}</strong><span class="event-result">${preview.details.map(e).join('<br>')}</span><span class="event-choice-hint">${preview.canChoose?'查看并确认选择':'条件不足'}</span></button></article>`;
 }).join('');
 return `<main class="app-shell event-screen">${hud}<section class="event-stage ${outcome?'is-outcome':''}" aria-label="${e(event.title)}"><img class="event-cg" src="${eventArtPath(data.id)}" alt="${e(event.title)}的场景插画" fetchpriority="high"><div class="event-location">第 ${state.act+1} 幕 · ${e(acts[state.act].name)} <span>${outcome?'02 / 事件发展':'01 / 遭遇'}</span></div><div class="event-story-wrap"><div class="event-story" aria-live="polite"><div class="event-kicker">${outcome?'此刻留下的回响':'来自城市的另一段频率'}</div><h2>${e(event.title)}</h2><p>${e(branch?branch.text:story.intro)}</p></div></div><div class="event-options-wrap"><div class="event-options" aria-label="${outcome?'事件结果':'可选行动'}">${options}</div></div></section></main>`;
}
