import {items,inventoryStatus,MAX_CAPACITY,MAX_ITEM_CAPACITY} from './core/inventory.js';
import {towers,relics,events} from './core/content.js';
import {shopPrice,servicePrice,eventPreview} from './core/state.js';
import * as Rules from './core/rules.js';
import {icon,sprite,escapeHTML as e,n,labels} from './ui.js';
import {unitEffectText} from './core/unit-details.js';
const button=(action,text,extra='',cls='primary')=>`<button class="btn ${cls}" data-action="${action}" ${extra}>${text}</button>`;
export function itemArt(id){const item=items[id];return `<span class="potion-art" style="--item-color:${item.color}" aria-hidden="true"><i></i><b>${icon(item.icon)}</b></span>`;}
export function itemBelt(state){const bag=inventoryStatus(state);return `<div class="item-belt" aria-label="应急道具">${Array.from({length:bag.itemCapacity},(_,i)=>{const entry=bag.items[i];return entry?`<button data-action="item-use" data-uid="${entry.uid}" title="${e(items[entry.type].name+' · '+items[entry.type].description)}" aria-label="使用${items[entry.type].name}">${itemArt(entry.type)}<small>${i+1}</small></button>`:`<span class="item-empty" title="空道具槽">${i+1}</span>`;}).join('')}</div>`;}
export function inventoryBody(state){
 const bag=inventoryStatus(state),canManage=['map','node','prep','nexus','interlude'].includes(state.phase),selling=state.phase==='node'&&state.currentNode.type==='shop';
 return `<div class="bag-summary ${bag.overflow?'danger-line':'cost-line'}"><strong>构造背包 ${bag.used} / ${bag.capacity}</strong><span>已部署 ${bag.deployed.length} 个 · 仓库 ${bag.stored.length} 个</span>${bag.overflow?`<p>已超出 ${bag.overflow} 格。进入下一节点前，请移除至少 ${bag.overflow} 个构造。</p>`:'<p>每个构造占 1 格，已部署者同时占用带宽。奖励可暂时超容量。</p>'}</div>
 <div class="bag-section-heading"><h3>应急道具 ${bag.items.length} / ${bag.itemCapacity}</h3><small>打开道具窗口时战斗暂停；确认后消耗一瓶</small></div><div class="bag-items">${bag.items.map(entry=>`<article class="bag-item">${itemArt(entry.type)}<div><strong>${items[entry.type].name}</strong><p>${items[entry.type].description}</p><div class="row">${button('item-use','查看 / 使用',`data-uid="${entry.uid}"`)}${button('item-discard','丢弃',`data-uid="${entry.uid}"`,'ghost')}</div></div></article>`).join('')||'<p class="muted">没有携带道具。战斗奖励、事件与商店可获得道具。</p>'}</div>
 <div class="bag-section-heading"><h3>全部构造</h3><small>${canManage?'勾选后确认永久移除，已部署者同时撤下防线':'当前阶段可查看；在路线、节点或战前整理'}</small></div><div class="bag-units">${bag.all.map(u=>`<label class="bag-unit ${Number.isFinite(u.x)?'is-deployed':''}"><input type="checkbox" data-discard-uid="${u.uid}" ${canManage?'':'disabled'}>${sprite(u.type,'towers','small',u)}<span><strong>${towers[u.type].name} · T${u.tier}${u.branch||''}</strong><small class="bag-location">${Number.isFinite(u.x)?`已部署 · ${u.x}, ${u.z}`:'仓库'}${u.hp<=0?' · 损毁':''}</small><small>${u.uid} · 耐久 ${n(u.hp)} / ${n(Rules.unitStats(state,u).maxHp)} · 带宽 ${Rules.unitStats(state,u).bandwidth}</small></span>${selling&&!Number.isFinite(u.x)?button('sell-unit',`回收 +${u.tier*20}`,`data-uid="${u.uid}"`,'ghost'):button('unit-info','详情',`data-uid="${u.uid}"`,'ghost')}</label>`).join('')||'<p class="empty">尚未拥有构造</p>'}</div>${canManage?button('bag-delete','移除所选构造','','danger'):''}`;
}
export function itemRewardBody(state){const reward=state.rewardQueue[0],id=reward.options[0],bag=inventoryStatus(state);return `<div class="item-reward"><article class="choice-card">${itemArt(id)}<h3>${items[id].name}</h3><p>${items[id].description}</p><div class="cost-line">道具槽 ${bag.items.length} / ${bag.itemCapacity}</div>${bag.items.length<bag.itemCapacity?button('reward','收进道具槽',`data-id="${id}"`):`<p>选择一瓶现有道具进行替换：</p>${bag.items.map(entry=>button('item-replace',`替换 ${items[entry.type].name}`,`data-id="${id}" data-uid="${entry.uid}"`,'ghost')).join('')}`}${button('item-skip','放弃这瓶道具','','ghost')}</article></div>`;}
export function shopBody(state){
 const node=state.currentNode,bag=inventoryStatus(state);
 const columns=[['units','心智构造'],['relics','收藏品'],['items','应急道具']].map(([kind,title])=>`<section class="shop-column"><h3 class="shop-category">${title} <small>0${(node.stock[kind]||[]).length}</small></h3><div class="shop-products">${(node.stock[kind]||[]).map(offer=>{const c=kind==='units'?towers[offer.id]:kind==='relics'?relics[offer.id]:items[offer.id],cost=shopPrice(state,kind,offer),tier=offer.tier||1,art=kind==='units'?sprite(offer.id,'towers','small',{tier,branch:offer.branch}):kind==='items'?itemArt(offer.id):icon('treasure');return `<article class="shop-product ${offer.sold?'sold':''}"><div class="shop-product-heading">${art}<div><h3>${c.name}</h3><small>${kind==='units'?`${labels[c.role]} · T${tier}${offer.branch||''}`:kind==='items'?'一次性消耗':c.theme}${offer.price<(kind==='units'?(tier===2?135:80):kind==='items'?c.price:120)?' · 特价':''}</small></div>${button(kind==='units'?'buy-unit':kind==='items'?'buy-item':'buy-relic',offer.sold?'已售出':`${cost} 专注`,`data-id="${offer.key}" ${offer.sold||state.focus<cost?'disabled':''}`)}</div><p>${e(kind==='units'?unitEffectText(state,{type:offer.id,tier,branch:offer.branch||null,hp:c.hp,x:null,z:null}):c.description)}</p>${kind==='units'&&offer.branch?`<small>分支：${c.branches[offer.branch].name}</small>`:''}</article>`;}).join('')||'<p class="muted">本局收藏品已集齐</p>'}</div></section>`).join('');
 return `<div class="shop-catalog">${columns}</div><div class="shop-services">${[['capacity','运输匣扩容',65,`背包 ${bag.capacity} → ${Math.min(MAX_CAPACITY,bag.capacity+2)} 格`,bag.capacity>=MAX_CAPACITY],['pouch','道具匣扩容',90,`道具槽 ${bag.itemCapacity} → ${Math.min(MAX_ITEM_CAPACITY,bag.itemCapacity+1)}`,bag.itemCapacity>=MAX_ITEM_CAPACITY],['heal','静频调理',40,`恢复 ${n(Math.min(20,state.maxSpirit-state.spirit))} 精神`,state.spirit>=state.maxSpirit]].map(([id,title,base,detail,full])=>`<article class="shop-service"><div><h3>${title}</h3><p>${detail} · 限一次</p></div>${button('shop-service',node.stock.services?.[id]?'已使用':`${servicePrice(state,base)} 专注`,`data-id="${id}" ${node.stock.services?.[id]||full||state.focus<servicePrice(state,base)?'disabled':''}`)}</article>`).join('')}</div><div class="row spread node-footer">${button('inventory','回收库存构造','','ghost')}${button('node-leave','离开商店')}</div>`;
}
export function eventBody(state){const event=events[state.currentNode.eventData.id],bag=inventoryStatus(state);return `<div class="event-intro">${icon('event')}<p>每项交换的实际得失在下方显示。选择材料后再确认。</p></div><div class="event-choice-grid">${event.choices.map((choice,index)=>{const preview=eventPreview(state,index),fx=choice.effects;return `<article class="panel panel-body" data-event-card="${index}"><div class="eyebrow">选择 0${index+1}</div><h3>${e(choice.label)}</h3>${fx.recycle?`<label class="field">选择回收构造<select data-event-unit="${index}">${bag.stored.map(u=>`<option value="${u.uid}" ${u.uid===preview.recycleUid?'selected':''}>${towers[u.type].name} T${u.tier}${u.branch||''} · ${u.uid}</option>`).join('')}</select></label>`:''}${fx.consume_item?`<label class="field">选择交出的道具<select data-event-item="${index}">${bag.items.map(item=>`<option value="${item.uid}" ${item.uid===preview.itemUid?'selected':''}>${items[item.type].name}</option>`).join('')}</select></label>`:''}<div class="event-result">${preview.details.map(e).join('<br>')}</div>${button('event-choice','确认这项交换',`data-index="${index}" ${preview.canChoose?'':'disabled'}`)}</article>`;}).join('')}</div>`;}
